<?php

namespace Article\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * articleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class articleRepository extends EntityRepository
{
	  public function search_result($search_entry)
  {
	  $qb = $this->createQueryBuilder('a');

	  $qb->where('a.title LIKE :keyword')
	  	 ->orWhere('a.text LIKE :keyword')
		 ->setParameter('keyword', '%'.$search_entry.'%');
		 
	  return $qb->getQuery()
				->getResult();
  }
  
    public function get_user_articles($id)
  {
	  $qb = $this->_em->createQueryBuilder();

	  $qb->select('a.title, a.text, a.timestamp')
		 ->from('ArticleArticleBundle:article', 'a')
		 ->where('a.id = :id')
		 ->setParameter('id', $id);

		return $qb->getQuery()
				->getResult();;
  }
}
