parameters:
#    article_article.example.class: Article\ArticleBundle\Example

services:
#    article_article.example:
#        class: %article_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
